##
# Run unit test and the action itself
##
name: Unit Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test